<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>TXTextControlWords_Ribbon</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <OutputPath>..\_Выход\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <OutputPath>..\_Выход\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="TX_Text_Control_Words\Icons.tx.ico" />
    <None Remove="TX_Text_Control_Words\Images.txwords_info.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Large.FinishAndMerge.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Large.Preview.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Large.FinishAndMerge.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Large.Preview.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.DataSource_LoadSample.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.FinishAndMerge.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.FinishAndMerge_IntoCurrentDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.FinishAndMerge_IntoIndividualDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.FinishAndMerge_IntoSingleFile.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.FinishAndMerge_PrintDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.FinishGroup.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.FormLayoutRTL.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.OpenDemo.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.Preview.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.DataSource_LoadSample.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.FinishAndMerge.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.FinishAndMerge_IntoCurrentDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.FinishAndMerge_IntoIndividualDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.FinishAndMerge_IntoSingleFile.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.FinishAndMerge_PrintDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.FinishGroup.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.FormLayoutRTL.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.OpenDemo.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.Preview.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.DataSource_LoadSample.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.FinishAndMerge.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.FinishAndMerge_IntoCurrentDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.FinishAndMerge_IntoIndividualDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.FinishAndMerge_IntoSingleFile.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.FinishAndMerge_PrintDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.FinishGroup.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.FormLayoutRTL.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Large.FormLayoutRTL.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Large.OpenDemo.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.OpenDemo.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.Preview.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.DataSource_LoadSample.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.FinishAndMerge.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.FinishAndMerge_IntoCurrentDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.FinishAndMerge_IntoIndividualDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.FinishAndMerge_IntoSingleFile.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.FinishAndMerge_PrintDocument.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.FinishGroup.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.FormLayoutRTL.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Large.FormLayoutRTL.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Large.OpenDemo.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.OpenDemo.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.Preview.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Large.FinishAndMerge.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Large.Preview.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Large.FinishAndMerge.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Large.Preview.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Small.AppViewGroup.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Small.AppViewGroup.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Small.AppViewGroup.png" />
    <None Remove="TX_Text_Control_Words\Images._64.Small.AppViewGroup.png" />
    <None Remove="TXTextControlWords_Ribbon.exe.licenses" />
    <EmbeddedResource Include="TX_Text_Control_Words\Icons.tx.ico" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images.txwords_info.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Large.FinishAndMerge.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Large.Preview.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Large.FinishAndMerge.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Large.Preview.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.DataSource_LoadSample.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.FinishAndMerge.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.FinishAndMerge_IntoCurrentDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.FinishAndMerge_IntoIndividualDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.FinishAndMerge_IntoSingleFile.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.FinishAndMerge_PrintDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.FinishGroup.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.FormLayoutRTL.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.OpenDemo.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.Preview.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.DataSource_LoadSample.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.FinishAndMerge.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.FinishAndMerge_IntoCurrentDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.FinishAndMerge_IntoIndividualDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.FinishAndMerge_IntoSingleFile.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.FinishAndMerge_PrintDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.FinishGroup.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.FormLayoutRTL.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.OpenDemo.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.Preview.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.DataSource_LoadSample.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.FinishAndMerge.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.FinishAndMerge_IntoCurrentDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.FinishAndMerge_IntoIndividualDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.FinishAndMerge_IntoSingleFile.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.FinishAndMerge_PrintDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.FinishGroup.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.FormLayoutRTL.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Large.FormLayoutRTL.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Large.OpenDemo.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.OpenDemo.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.Preview.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.DataSource_LoadSample.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.FinishAndMerge.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.FinishAndMerge_IntoCurrentDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.FinishAndMerge_IntoIndividualDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.FinishAndMerge_IntoSingleFile.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.FinishAndMerge_PrintDocument.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.FinishGroup.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.FormLayoutRTL.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Large.FormLayoutRTL.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Large.OpenDemo.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.OpenDemo.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.Preview.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Large.FinishAndMerge.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Large.Preview.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Large.FinishAndMerge.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Large.Preview.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Small.AppViewGroup.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Small.AppViewGroup.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Small.AppViewGroup.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._64.Small.AppViewGroup.png" />
    <EmbeddedResource Include="TXTextControlWords_Ribbon.exe.licenses" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TXTextControl\TXTextControl.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>