<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>TXTextControlWords</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <OutputPath>..\_Выход\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <OutputPath>..\_Выход\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="TX_Text_Control_Words\Icons.tx.ico" />
    <None Remove="TX_Text_Control_Words\Images.txwords_info.png" />
    <None Remove="TX_Text_Control_Words\Images._16.FormLayoutRTL.png" />
    <None Remove="TX_Text_Control_Words\Images._24.FormLayoutRTL.png" />
    <None Remove="TX_Text_Control_Words\Images._32.FormLayoutRTL.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Charts.ClusteredBar.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Charts.Pie.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Charts.StackedArea100Percent.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Charts.StackedBar.png" />
    <None Remove="TX_Text_Control_Words\Images._16.Charts.StackedColumn100Percent.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Charts.ClusteredBar.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Charts.Pie.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Charts.StackedArea100Percent.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Charts.StackedBar.png" />
    <None Remove="TX_Text_Control_Words\Images._24.Charts.StackedColumn100Percent.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Charts.ClusteredBar.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Charts.Pie.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Charts.StackedArea100Percent.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Charts.StackedBar.png" />
    <None Remove="TX_Text_Control_Words\Images._32.Charts.StackedColumn100Percent.png" />
    <None Remove="TXTextControlWords.exe.licenses" />
    <EmbeddedResource Include="TX_Text_Control_Words\Icons.tx.ico" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images.txwords_info.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.FormLayoutRTL.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.FormLayoutRTL.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.FormLayoutRTL.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Charts.ClusteredBar.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Charts.Pie.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Charts.StackedArea100Percent.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Charts.StackedBar.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._16.Charts.StackedColumn100Percent.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Charts.ClusteredBar.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Charts.Pie.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Charts.StackedArea100Percent.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Charts.StackedBar.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._24.Charts.StackedColumn100Percent.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Charts.ClusteredBar.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Charts.Pie.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Charts.StackedArea100Percent.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Charts.StackedBar.png" />
    <EmbeddedResource Include="TX_Text_Control_Words\Images._32.Charts.StackedColumn100Percent.png" />
    <EmbeddedResource Include="TXTextControlWords.exe.licenses" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TXTextControl\TXTextControl.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms.DataVisualization" />
    <Reference Include="System.Core" />
  </ItemGroup>
</Project>