using System;

namespace LocmanWebServer
{
    // Клиентская логика (JavaScript) встроена в сборку, чтобы сервер был
    // единым .exe без внешних файлов.
    public static class Scripts
    {
        public static string AppJs
        {
            get
            {
                return "'use strict';\n"
                    + "var $ = function (id) { return document.getElementById(id); };\n"
                    + "var statusEl = $('status');\n"
                    + "\n"
                    + "function setStatus(t, isErr) {\n"
                    + "  statusEl.innerHTML = isErr ? '<span class=\"err\">' + t + '</span>' : t;\n"
                    + "}\n"
                    + "\n"
                    + "function get(url) {\n"
                    + "  return fetch(url).then(function (r) {\n"
                    + "    if (!r.ok) throw new Error('HTTP ' + r.status);\n"
                    + "    return r.json();\n"
                    + "  });\n"
                    + "}\n"
                    + "\n"
                    + "function fill(sel, items, placeholder) {\n"
                    + "  sel.innerHTML = '';\n"
                    + "  var op = document.createElement('option');\n"
                    + "  op.value = ''; op.textContent = placeholder;\n"
                    + "  sel.appendChild(op);\n"
                    + "  items.forEach(function (it) {\n"
                    + "    var o = document.createElement('option');\n"
                    + "    if (typeof it === 'object') { o.value = it.value; o.textContent = it.name; }\n"
                    + "    else { o.value = it; o.textContent = it; }\n"
                    + "    sel.appendChild(o);\n"
                    + "  });\n"
                    + "}\n"
                    + "\n"
                    + "function addrParams() {\n"
                    + "  return { city: $('city').value, street: $('street').value, house: $('house').value };\n"
                    + "}\n"
                    + "\n"
                    + "function selectedFlats() {\n"
                    + "  var arr = [];\n"
                    + "  document.querySelectorAll('#flatList input:checked').forEach(function (cb) {\n"
                    + "    arr.push(cb.value);\n"
                    + "  });\n"
                    + "  return arr;\n"
                    + "}\n"
                    + "\n"
                    + "function openReport(kind, format, flats) {\n"
                    + "  var a = addrParams();\n"
                    + "  var url = '/report?format=' + encodeURIComponent(format) +\n"
                    + "            '&kind=' + kind +\n"
                    + "            '&city=' + encodeURIComponent(a.city) +\n"
                    + "            '&street=' + encodeURIComponent(a.street) +\n"
                    + "            '&house=' + encodeURIComponent(a.house) +\n"
                    + "            '&flats=' + encodeURIComponent(flats.join(','));\n"
                    + "  window.location.href = url;\n"
                    + "  setStatus('Формируется отчёт (' + format.toUpperCase() + ')…');\n"
                    + "}\n"
                    + "\n"
                    + "// ---------- Каскад: город -> улица -> дом -> квартиры ----------\n"
                    + "\n"
                    + "$('city').onchange = function () {\n"
                    + "  $('street').innerHTML = '<option value=\"\">— загрузка… —</option>';\n"
                    + "  $('house').innerHTML = '<option value=\"\">— сначала выберите улицу —</option>';\n"
                    + "  $('flatsCard').style.display = 'none';\n"
                    + "  $('residentsCard').style.display = 'none';\n"
                    + "  if (!this.value) return;\n"
                    + "  setStatus('Загрузка улиц…');\n"
                    + "  get('/api/streets?city=' + encodeURIComponent(this.value))\n"
                    + "    .then(function (list) { fill($('street'), list, '— выберите улицу —'); setStatus('Улиц загружено: ' + list.length); })\n"
                    + "    .catch(function (e) { setStatus('Ошибка загрузки улиц: ' + e.message, true); });\n"
                    + "};\n"
                    + "\n"
                    + "$('street').onchange = function () {\n"
                    + "  $('house').innerHTML = '<option value=\"\">— загрузка… —</option>';\n"
                    + "  $('flatsCard').style.display = 'none';\n"
                    + "  $('residentsCard').style.display = 'none';\n"
                    + "  if (!this.value) return;\n"
                    + "  setStatus('Загрузка домов…');\n"
                    + "  get('/api/houses?city=' + encodeURIComponent(addrParams().city) +\n"
                    + "      '&street=' + encodeURIComponent(this.value))\n"
                    + "    .then(function (list) { fill($('house'), list, '— выберите дом —'); setStatus('Домов: ' + list.length); })\n"
                    + "    .catch(function (e) { setStatus('Ошибка загрузки домов: ' + e.message, true); });\n"
                    + "};\n"
                    + "\n"
                    + "$('house').onchange = function () {\n"
                    + "  $('residentsCard').style.display = 'none';\n"
                    + "  if (!this.value) { $('flatsCard').style.display = 'none'; return; }\n"
                    + "  setStatus('Загрузка квартир…');\n"
                    + "  var a = addrParams();\n"
                    + "  get('/api/flats?city=' + encodeURIComponent(a.city) +\n"
                    + "      '&street=' + encodeURIComponent(a.street) +\n"
                    + "      '&house=' + encodeURIComponent(a.house))\n"
                    + "    .then(function (list) {\n"
                    + "      var box = $('flatList');\n"
                    + "      box.innerHTML = '';\n"
                    + "      list.forEach(function (f) {\n"
                    + "        var l = document.createElement('label');\n"
                    + "        var cb = document.createElement('input');\n"
                    + "        cb.type = 'checkbox'; cb.value = f.num;\n"
                    + "        l.appendChild(cb);\n"
                    + "        l.appendChild(document.createTextNode(' кв. ' + f.num));\n"
                    + "        box.appendChild(l);\n"
                    + "      });\n"
                    + "      $('flatsCard').style.display = list.length ? '' : 'none';\n"
                    + "      setStatus('Квартир найдено: ' + list.length + '. Отметьте нужные и выберите действие.');\n"
                    + "    })\n"
                    + "    .catch(function (e) { setStatus('Ошибка загрузки квартир: ' + e.message, true); });\n"
                    + "};\n"
                    + "\n"
                    + "$('selAll').onclick = function (e) {\n"
                    + "  e.preventDefault();\n"
                    + "  document.querySelectorAll('#flatList input').forEach(function (cb) { cb.checked = true; });\n"
                    + "};\n"
                    + "$('selNone').onclick = function (e) {\n"
                    + "  e.preventDefault();\n"
                    + "  document.querySelectorAll('#flatList input').forEach(function (cb) { cb.checked = false; });\n"
                    + "};\n"
                    + "\n"
                    + "// ---------- Действия со списком квартир ----------\n"
                    + "\n"
                    + "$('runFlats').onclick = function () {\n"
                    + "  var act = $('flatsAction').value;\n"
                    + "  if (!act) { setStatus('Выберите действие из списка.', true); return; }\n"
                    + "  var flats = selectedFlats();\n"
                    + "  if (act.indexOf('report_') === 0) {\n"
                    + "    if (!flats.length) { setStatus('Отметьте хотя бы одну квартиру.', true); return; }\n"
                    + "    openReport('flats', act.substring(7), flats);\n"
                    + "  } else if (act === 'show_residents') {\n"
                    + "    if (!flats.length) { setStatus('Отметьте хотя бы одну квартиру.', true); return; }\n"
                    + "    showResidents(flats, 'Жители выбранных квартир');\n"
                    + "  } else if (act === 'show_all') {\n"
                    + "    showResidents([], 'Жители дома (все квартиры)');\n"
                    + "  }\n"
                    + "};\n"
                    + "\n"
                    + "var lastFlatsParam = '';\n"
                    + "function showResidents(flats, title) {\n"
                    + "  var a = addrParams();\n"
                    + "  lastFlatsParam = flats.join(',');\n"
                    + "  $('resTitle').textContent = title + ': ' + a.city + ', ' + a.street + ', д. ' + a.house;\n"
                    + "  $('residentsCard').style.display = '';\n"
                    + "  $('resTable').innerHTML = '<span class=\"muted\">Загрузка жителей…</span>';\n"
                    + "  setStatus('Загрузка жителей…');\n"
                    + "  get('/api/residents?city=' + encodeURIComponent(a.city) +\n"
                    + "      '&street=' + encodeURIComponent(a.street) +\n"
                    + "      '&house=' + encodeURIComponent(a.house) +\n"
                    + "      '&flats=' + encodeURIComponent(lastFlatsParam))\n"
                    + "    .then(function (list) { renderResidents(list); setStatus('Жителей найдено: ' + list.length); })\n"
                    + "    .catch(function (e) {\n"
                    + "      $('resTable').innerHTML = '';\n"
                    + "      setStatus('Ошибка загрузки жителей: ' + e.message, true);\n"
                    + "    });\n"
                    + "}\n"
                    + "\n"
                    + "function renderResidents(list) {\n"
                    + "  if (!list.length) { $('resTable').innerHTML = '<span class=\"muted\">Жители не найдены.</span>'; return; }\n"
                    + "  var h = '<table><tr><th>Квартира</th><th>Ф.И.О.</th><th>Тип договора</th><th>Дата записи</th></tr>';\n"
                    + "  list.forEach(function (r) {\n"
                    + "    h += '<tr><td>' + esc(r.flat) + '</td><td>' + esc(r.fio) + '</td><td>' +\n"
                    + "         esc(r.contract) + '</td><td>' + esc(r.date) + '</td></tr>';\n"
                    + "  });\n"
                    + "  h += '</table>';\n"
                    + "  $('resTable').innerHTML = h;\n"
                    + "}\n"
                    + "\n"
                    + "function esc(s) {\n"
                    + "  return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');\n"
                    + "}\n"
                    + "\n"
                    + "// ---------- Действия со списком жителей ----------\n"
                    + "\n"
                    + "$('runRes').onclick = function () {\n"
                    + "  var act = $('resAction').value;\n"
                    + "  if (!act) { setStatus('Выберите действие из списка.', true); return; }\n"
                    + "  if (act.indexOf('report_') === 0)\n"
                    + "    openReport('residents', act.substring(7), lastFlatsParam ? lastFlatsParam.split(',') : []);\n"
                    + "};\n"
                    + "\n"
                    + "// ---------- Старт ----------\n"
                    + "\n"
                    + "get('/api/cities')\n"
                    + "  .then(function (list) { fill($('city'), list, '— выберите город —'); setStatus('Готово. Выберите город.'); })\n"
                    + "  .catch(function (e) { setStatus('Ошибка загрузки городов: ' + e.message, true); });\n"
                    + "\n";
            }
        }
    }
}
