<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>txHelpCenter</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net40</TargetFramework>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>Preview</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="tx_help_center_2014\ImgResources.icon_reporting.png" />
    <None Remove="tx_help_center_2014\ImgResources.back_blue.png" />
    <None Remove="tx_help_center_2014\ImgResources.back_gray.png" />
    <None Remove="tx_help_center_2014\ImgResources.back.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_documentation.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_gettingstarted.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_updates.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_support.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_blog.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_key.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_html5.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_vs.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_window.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_html5.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_sps.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_folder.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_reporting.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_richtext.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_txwords.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_samples.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_documentation.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_support.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_blog.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_up.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_shopping.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_spell.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_check.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_facebook.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_googleplus.png" />
    <None Remove="tx_help_center_2014\ImgResources.icon_twitter.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_main.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_whatsnew.png" />
    <None Remove="tx_help_center_2014\ImgResources.github.png" />
    <None Remove="tx_help_center_2014\ImgResources.screenshot_github.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_reporting.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.back_blue.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.back_gray.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.back.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_documentation.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_gettingstarted.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_updates.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_support.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_blog.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_key.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_html5.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_vs.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_window.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_html5.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_sps.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_folder.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_reporting.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_richtext.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_txwords.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_samples.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_documentation.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_support.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_blog.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_up.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_shopping.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_spell.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_check.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_facebook.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_googleplus.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.icon_twitter.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_main.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_whatsnew.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.github.png" />
    <EmbeddedResource Include="tx_help_center_2014\ImgResources.screenshot_github.png" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Xml" />
  </ItemGroup>
</Project>